# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('performer', models.CharField(max_length=100, null=True)),
                ('album', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateField(null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('play_count', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('year', models.IntegerField(null=True)),
                ('track_number', models.IntegerField(null=True)),
                ('file_size', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('date_added', models.DateField()),
                ('genre', models.CharField(max_length=50, null=True)),
                ('play_count', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('year', models.IntegerField(null=True)),
                ('file_size', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
            ],
        ),
    ]
