# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='track_number',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='year',
            field=models.FloatField(null=True),
        ),
    ]
