# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0002_videotrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='album',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='song_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='video_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
