# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0002_auto_20160712_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='year',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
