# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0004_auto_20160711_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='file_size',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
