# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0005_auto_20160711_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotrack',
            name='file_size',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='play_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
