# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0005_auto_20160712_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='date_added',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='file_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='play_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='track_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
