# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0006_auto_20160711_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='performer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
