# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0006_auto_20160712_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotrack',
            name='file_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='date_added',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='file_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videotrack',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
