# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0007_auto_20160718_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotrack',
            name='bit_rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videotrack',
            name='video_length',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
