# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0007_audiotrack_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
