# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0009_auto_20160718_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotrack',
            name='date_added',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 18, 18, 22, 36, 530079, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
