# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0010_auto_20160718_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotrack',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
