# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0012_auto_20160718_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
